/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Product;
import Business.ProDemographic;
import Business.ProAddress;
import Business.ProAccount;
import Business.ProLicense;
import Business.ProMedical;
/**
 *
 * @author dell
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Product product;
    private ProDemographic proDemographic;
    private ProAddress proAddress;
    private ProAccount proAccount;
    private ProLicense proLicense;
    private ProMedical proMedical;
    
    public MainJFrame() {
        initComponents();
        product = new Product();
        proDemographic = new ProDemographic();
        proAddress = new ProAddress();
        proAccount = new ProAccount();
        proLicense = new ProLicense();
        proMedical = new ProMedical();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlJPanel = new javax.swing.JPanel();
        createDemographicBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        createAddressBtn = new javax.swing.JButton();
        createAccountBtn = new javax.swing.JButton();
        createLicenseBtn = new javax.swing.JButton();
        createMedicalBtn = new javax.swing.JButton();
        viewDemographicBtn = new javax.swing.JButton();
        viewAddressBtn = new javax.swing.JButton();
        viewAccountBtn = new javax.swing.JButton();
        viewLicenseBtn = new javax.swing.JButton();
        viewMedicalBtn = new javax.swing.JButton();
        displayJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlJPanel.setBackground(new java.awt.Color(153, 153, 153));

        createDemographicBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        createDemographicBtn.setText("Create Demographic Info");
        createDemographicBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createDemographicBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDemographicBtnActionPerformed(evt);
            }
        });

        viewBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        viewBtn.setText("View");
        viewBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        createAddressBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        createAddressBtn.setText("Create Address Info");
        createAddressBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createAddressBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAddressBtnActionPerformed(evt);
            }
        });

        createAccountBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        createAccountBtn.setText("Create Account Info");
        createAccountBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountBtnActionPerformed(evt);
            }
        });

        createLicenseBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        createLicenseBtn.setText("Create License Info");
        createLicenseBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createLicenseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createLicenseBtnActionPerformed(evt);
            }
        });

        createMedicalBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        createMedicalBtn.setText("Create Medical Record");
        createMedicalBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createMedicalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMedicalBtnActionPerformed(evt);
            }
        });

        viewDemographicBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        viewDemographicBtn.setText("View Demographic Info");
        viewDemographicBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewDemographicBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDemographicBtnActionPerformed(evt);
            }
        });

        viewAddressBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        viewAddressBtn.setText("View Address Info");
        viewAddressBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewAddressBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAddressBtnActionPerformed(evt);
            }
        });

        viewAccountBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        viewAccountBtn.setText("View Account Info");
        viewAccountBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAccountBtnActionPerformed(evt);
            }
        });

        viewLicenseBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        viewLicenseBtn.setText("View License Info");
        viewLicenseBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewLicenseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLicenseBtnActionPerformed(evt);
            }
        });

        viewMedicalBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        viewMedicalBtn.setText("View Medical Record");
        viewMedicalBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewMedicalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMedicalBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlJPanelLayout = new javax.swing.GroupLayout(controlJPanel);
        controlJPanel.setLayout(controlJPanelLayout);
        controlJPanelLayout.setHorizontalGroup(
            controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createDemographicBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createAddressBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createAccountBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createLicenseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createMedicalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewDemographicBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewAddressBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewAccountBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewLicenseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewMedicalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        controlJPanelLayout.setVerticalGroup(
            controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlJPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(createDemographicBtn)
                .addGap(18, 18, 18)
                .addComponent(createAddressBtn)
                .addGap(18, 18, 18)
                .addComponent(createAccountBtn)
                .addGap(18, 18, 18)
                .addComponent(createLicenseBtn)
                .addGap(18, 18, 18)
                .addComponent(createMedicalBtn)
                .addGap(18, 18, 18)
                .addComponent(viewDemographicBtn)
                .addGap(18, 18, 18)
                .addComponent(viewAddressBtn)
                .addGap(18, 18, 18)
                .addComponent(viewAccountBtn)
                .addGap(18, 18, 18)
                .addComponent(viewLicenseBtn)
                .addGap(18, 18, 18)
                .addComponent(viewMedicalBtn)
                .addGap(18, 18, 18)
                .addComponent(viewBtn)
                .addGap(215, 215, 215))
        );

        splitPane.setLeftComponent(controlJPanel);

        displayJPanel.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout displayJPanelLayout = new javax.swing.GroupLayout(displayJPanel);
        displayJPanel.setLayout(displayJPanelLayout);
        displayJPanelLayout.setHorizontalGroup(
            displayJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 753, Short.MAX_VALUE)
        );
        displayJPanelLayout.setVerticalGroup(
            displayJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(displayJPanel);

        getContentPane().add(splitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createDemographicBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDemographicBtnActionPerformed
        CreateDemographicJPanel createDemographicJPanel = new CreateDemographicJPanel(proDemographic);
        splitPane.setRightComponent(createDemographicJPanel);
    }//GEN-LAST:event_createDemographicBtnActionPerformed

    private void createAddressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAddressBtnActionPerformed
        CreateAddressJPanel createAddressJPanel = new CreateAddressJPanel(proAddress);
        splitPane.setRightComponent(createAddressJPanel);
    }//GEN-LAST:event_createAddressBtnActionPerformed

    private void createAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountBtnActionPerformed
        CreateAccountJPanel createAccountJPanel = new CreateAccountJPanel(proAccount);
        splitPane.setRightComponent(createAccountJPanel);
    }//GEN-LAST:event_createAccountBtnActionPerformed

    private void createLicenseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createLicenseBtnActionPerformed
        CreateLicenseJPanel createLicenseJPanel = new CreateLicenseJPanel(proLicense);
        splitPane.setRightComponent(createLicenseJPanel);
    }//GEN-LAST:event_createLicenseBtnActionPerformed

    private void createMedicalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMedicalBtnActionPerformed
         CreateMedicalJPanel createMedicalJPanel = new CreateMedicalJPanel(proMedical);
         splitPane.setRightComponent(createMedicalJPanel);
    }//GEN-LAST:event_createMedicalBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        ViewJPanel viewJPanel = new ViewJPanel(proDemographic, proAddress, proAccount, proLicense, proMedical);
        splitPane.setRightComponent(viewJPanel);
    }//GEN-LAST:event_viewBtnActionPerformed

    private void viewDemographicBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDemographicBtnActionPerformed
        ViewDemographicJPanel viewDemographicJPanel = new ViewDemographicJPanel(proDemographic);
        splitPane.setRightComponent(viewDemographicJPanel);
    }//GEN-LAST:event_viewDemographicBtnActionPerformed

    private void viewAddressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAddressBtnActionPerformed
        ViewAddressJPanel viewAddressJPanel = new ViewAddressJPanel(proAddress);
        splitPane.setRightComponent(viewAddressJPanel);
    }//GEN-LAST:event_viewAddressBtnActionPerformed

    private void viewAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAccountBtnActionPerformed
        ViewAccountJPanel viewAccountJPanel = new ViewAccountJPanel(proAccount);
        splitPane.setRightComponent(viewAccountJPanel);
    }//GEN-LAST:event_viewAccountBtnActionPerformed

    private void viewLicenseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLicenseBtnActionPerformed
        ViewLicenseJPanel viewLicenseJPanel = new ViewLicenseJPanel(proLicense);
        splitPane.setRightComponent(viewLicenseJPanel);
    }//GEN-LAST:event_viewLicenseBtnActionPerformed

    private void viewMedicalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMedicalBtnActionPerformed
        ViewMedicalJPanel viewMedicalJPanel = new ViewMedicalJPanel(proMedical);
        splitPane.setRightComponent(viewMedicalJPanel);
    }//GEN-LAST:event_viewMedicalBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlJPanel;
    private javax.swing.JButton createAccountBtn;
    private javax.swing.JButton createAddressBtn;
    private javax.swing.JButton createDemographicBtn;
    private javax.swing.JButton createLicenseBtn;
    private javax.swing.JButton createMedicalBtn;
    private javax.swing.JPanel displayJPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JButton viewAccountBtn;
    private javax.swing.JButton viewAddressBtn;
    private javax.swing.JButton viewBtn;
    private javax.swing.JButton viewDemographicBtn;
    private javax.swing.JButton viewLicenseBtn;
    private javax.swing.JButton viewMedicalBtn;
    // End of variables declaration//GEN-END:variables
}
