/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Product;
import Business.ProAccount;

/**
 *
 * @author dell
 */
public class ViewAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAccountJPanel
     */
    public ViewAccountJPanel(ProAccount proAccount) {
        initComponents();
        displayProduct(proAccount);
    }
    
    private void displayProduct(ProAccount proAccount)
    {
        String productsbankname = proAccount.getSBankName();
        SbanknameTextField.setText(productsbankname);
        
        String productsroutingnumber = proAccount.getSRoutingNumber();
        SroutingnumberTextField.setText(productsroutingnumber);
        
        String productsaccountnumber = proAccount.getSAccountNumber();
        SaccountnumberTextField.setText(productsaccountnumber);
        
        String productsaccountbalance = proAccount.getSAccountBalance();
        SaccountbalanceTextField.setText(productsaccountbalance);
        
        String productsaccounttype = proAccount.getSAccountType();
        SaccounttypeTextField.setText(productsaccounttype);
        
        String productcbankname = proAccount.getCBankName();
        CbanknameTextField.setText(productcbankname);
        
        String productcroutingnumber = proAccount.getCRoutingNumber();
        CroutingnumberTextField.setText(productcroutingnumber);
        
        String productcaccountnumber = proAccount.getCAccountNumber();
        CaccountnumberTextField.setText(productcaccountnumber);
        
        String productcaccountbalance = proAccount.getCAccountBalance();
        CaccountbalanceTextField.setText(productcaccountbalance);
        
        String productcaccounttype = proAccount.getCAccountType();
        CaccounttypeTextField.setText(productcaccounttype);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SbanknameTextField = new javax.swing.JTextField();
        SroutingnumberTextField = new javax.swing.JTextField();
        SaccountnumberTextField = new javax.swing.JTextField();
        SaccountbalanceTextField = new javax.swing.JTextField();
        SaccounttypeTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        CbanknameTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CroutingnumberTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        CaccountnumberTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        CaccountbalanceTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        CaccounttypeTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("View Saving/Checking Account Information");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Saving");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Checking");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("S Bank Name :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("S Bank Routing Number :");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("S Bank Account Number :");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("S Account Balance :");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("S Account Type :");

        SbanknameTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        SroutingnumberTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        SaccountnumberTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        SaccountnumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaccountnumberTextFieldActionPerformed(evt);
            }
        });

        SaccountbalanceTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        SaccounttypeTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        SaccounttypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaccounttypeTextFieldActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("C Bank Name :");

        CbanknameTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("C Bank Routing Number :");

        CroutingnumberTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("C Bank Account Number :");

        CaccountnumberTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        CaccountnumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaccountnumberTextFieldActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("C Account Balance :");

        CaccountbalanceTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("C Account Type :");

        CaccounttypeTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        CaccounttypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaccounttypeTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(125, 125, 125)
                            .addComponent(jLabel2)
                            .addGap(221, 221, 221)
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(SbanknameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(SroutingnumberTextField)
                                .addComponent(SaccountnumberTextField)
                                .addComponent(SaccountbalanceTextField)
                                .addComponent(SaccounttypeTextField))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel12)
                                .addComponent(jLabel10)
                                .addComponent(jLabel9)
                                .addComponent(jLabel11))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CbanknameTextField)
                                .addComponent(CroutingnumberTextField)
                                .addComponent(CaccountnumberTextField)
                                .addComponent(CaccountbalanceTextField)
                                .addComponent(CaccounttypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(99, 99, 99)
                            .addComponent(jLabel1)
                            .addGap(98, 98, 98)))
                    .addContainerGap(32, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addGap(37, 37, 37)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(SbanknameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(SroutingnumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(SaccountnumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(SaccountbalanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(SaccounttypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(CbanknameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(CroutingnumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(CaccountnumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(CaccountbalanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(CaccounttypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(42, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SaccountnumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaccountnumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaccountnumberTextFieldActionPerformed

    private void SaccounttypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaccounttypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaccounttypeTextFieldActionPerformed

    private void CaccountnumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaccountnumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaccountnumberTextFieldActionPerformed

    private void CaccounttypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaccounttypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaccounttypeTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CaccountbalanceTextField;
    private javax.swing.JTextField CaccountnumberTextField;
    private javax.swing.JTextField CaccounttypeTextField;
    private javax.swing.JTextField CbanknameTextField;
    private javax.swing.JTextField CroutingnumberTextField;
    private javax.swing.JTextField SaccountbalanceTextField;
    private javax.swing.JTextField SaccountnumberTextField;
    private javax.swing.JTextField SaccounttypeTextField;
    private javax.swing.JTextField SbanknameTextField;
    private javax.swing.JTextField SroutingnumberTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
